# flac_config.toml
# Configuration for FLAC Tagging Application

[preferences]
# Set the year format for tags.
# Valid options: "YYYY" or "YY"
year_format = "YYYY"
segue_string = "->"
soundboard_abbrev = "SBD"
aud_abbrev = "AUD"
matrix_abbrev = "MTX"
ultramatrix_abbrev = "Ultramatrix"
verbose_logging = false
enable_filename_fallback = false

[album_tag]
# Toggle inclusion of optional components in the album tag.
include_bitrate = true
include_bitrate_not16_only = true # if true, only include the bitrate if it is not 16 bit
include_shnid    = true
include_venue   = false
include_city    = true

# Specify the order in which the selected components should appear.
# Valid values: "bitrate", "venue", "city", "recording_type" , "shnid", "show_date", 
# if items are excluded by the above variables, they will be ignored in the order list.
order = ["show_date","city","venue", "recording_type", "shnid","bitrate"]
#use the below lists to add a string before or after each of the sections above. 
#Include any spaces that are desired between elements in either the prefix or suffix. 
#NOTE: These lists must be the same length as the order list above, otherwise these lists will be ignored completely
prefix = ['',' ',' ',' ',' (',' [']
suffix = ['','','','',')',']']
# Specify the directories to search for artwork. Directories are grouped by
# artist abbreviation. Under each folder, files are organized in subdirectories
# by year. A search will append the year to the folder and look for files named
# "<artist_abbrev><concert_date>*.jpg". For example:
#   "GD_Art/TV_Artwork/1975/gd1975-03-23-Kezar-Stadium.jpg"
# would match the Grateful Dead show on 1975-03-23 unless a file exists in
# "GD_Art/EE_Artwork/" for the same date.

[cover]
clear_existing_artwork = false # Clears existing artwork tags and sets a new one
retain_existing_artwork = true # If an existing folder.{ext} file exists, append its name w/".old", even if the tag is overwritten

[cover.default_images]
# Map artist abbreviations to fallback artwork.
gd = 'GD_Art/default.jpg'

[cover.artwork_folders]
gd = ['GD_Art/EE_Artwork/', 'GD_Art/TV_Artwork/']
# Add additional entries keyed by artist abbreviation.
# If an abbreviation is missing, artwork tagging is skipped for that artist.



# Additional configuration settings can be added below.
[supportfiles]
#flac = "K:/Flac/flac.exe"
#metaflac = "K:/Flac/metaflac.exe"
flac = "K:/Flac/flac-1.5.0-win/Win64/flac.exe"
metaflac = "K:/Flac/flac-1.5.0-win/Win64/metaflac.exe"
oldflac = "K:/Flac/flac-1.3.2-win/win64/flac.exe"
#metaflac = "K:/Flac/flac-1.3.2-win/win64/metaflac.exe"
artistexceptions = "E:/My Documents/GitHub/lossless_music_tools/artist_exceptions.txt"
shorten = "K:/Flac/shorten.exe"
shntool = "K:/Flac/shntool.exe"

[recording_folder.standardize_artist_abbrev]
jg = ["jgb", "jg+jk", "jgjk", "jgms","lom"]

